name: "Daily Build"
on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'
jobs:
  build-micifuz-modules:
    name: Build Micifuz
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 17 ]
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Install JDK {{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          check-latest: true
      - name: Build the code
        run: mvn -fae -V -B clean test -Pcoverage,authn,petshop,shelters,vets
      - name: Generate Jacoco Report
        run: |
          cd coverage-report
          mvn package
      - name: Generate Jacoco Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: coverage-report/target/site/jacoco/jacoco.csv
      - name: Coverage Preparation
        id: coverage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          if [[ `git status | grep .svg | wc -l` > 0 ]]; then
            echo ::set-output name=needs-commit-badge::true
          else
            echo ::set-output name=needs-commit-badge::false
          fi
      - name: Commit the badge (if it changed)
        if: steps.coverage.outputs.needs-commit-badge == 'true'
        run: |
          git config --global user.name 'micifuz-master'
          git config --global user.email 'micifuz-master@users.noreply.github.com'
          git add *.svg
          git commit -m "Autogenerated JaCoCo coverage badge"
      - name: Push the badge (if it changed)
        if: steps.coverage.outputs.needs-commit-badge == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
      - name: Zip Artifacts
        if: failure()
        run: |
          zip -R build-micifuz-modules${{ matrix.java }}.zip '*-reports/*'
      - name: Archive artifacts
        if: failure()
        uses: actions/upload-artifact@v2.3.0
        with:
          name: ci-artifacts
          path: build-micifuz-modules${{ matrix.java }}.zip
      - name: Archive Coverage Report
        uses: actions/upload-artifact@v2.3.0
        with:
          name: ci-coverage
          path: coverage-report/target/site/jacoco
